"use client";

import { useState } from "react";

// Metadata removed as this is now a client component

type Cycle = "monthly" | "quarterly" | "annual";

const CYCLES: { id: Cycle; label: string; badge?: string }[] = [
  { id: "monthly", label: "Monthly" },
  { id: "quarterly", label: "3 Months", badge: "Save 10%" },
  { id: "annual", label: "Annual", badge: "1 month free" },
];

// Base monthly list price per plan.
const BASE_MONTHLY: Record<"pro" | "elite", number> = { pro: 14.99, elite: 29.99 };

function priceFor(plan: "pro" | "elite", cycle: Cycle): { perMonth: string; note: string } {
  const m = BASE_MONTHLY[plan];
  if (cycle === "quarterly") {
    const total = m * 3 * 0.9; // 10% off
    return { perMonth: (total / 3).toFixed(2), note: `$${total.toFixed(2)} billed every 3 months · save 10%` };
  }
  if (cycle === "annual") {
    const total = m * 11; // pay 11, get 12 → 1 month free
    return { perMonth: (total / 12).toFixed(2), note: `$${total.toFixed(2)} billed yearly · 1 month free` };
  }
  return { perMonth: m.toFixed(2), note: "billed monthly" };
}

const FAQ = [
  {
    q: "Are these official IELTS or TOEFL scores?",
    a: "No. PracticeForge is an independent AI study tool. All estimated scores and feedback are generated by AI for self-study guidance and are not affiliated with official examination organisations.",
  },
  {
    q: "How does the daily limit on Free work?",
    a: "On the Starter (Free) plan, you can generate 1 full practice session (including up to 15 reading questions) every 24 hours. The limit resets at midnight UTC.",
  },
  {
    q: "How do 'Speaking Tokens' work in Elite Mastery?",
    a: "Our AI Speaking Evaluator uses extremely advanced audio models. To keep costs sustainable while providing high quality, the Elite plan includes a generous daily token limit that equates to about 5 full speaking mock tests per day.",
  },
  {
    q: "Can I cancel anytime?",
    a: "Yes. There are no long-term contracts. Cancel your subscription at any time, and you retain access to your premium features until the end of your current billing period.",
  },
  {
    q: "Do you offer refunds?",
    a: "We offer a 7-day money-back guarantee if you are not satisfied with the Pro or Elite features. Just reach out to support.",
  },
];

export default function PricingPage() {
  const [cycle, setCycle] = useState<Cycle>("annual");

  const handleUpgrade = async (tier: "guest" | "free" | "pro" | "elite") => {
    // Free tier needs no payment.
    if (tier === "free" || tier === "guest") {
      localStorage.setItem("practiceforge_tier", tier);
      window.location.href = "/practice";
      return;
    }

    // Paid tiers: try real Stripe Checkout, fall back to the demo flow.
    try {
      const res = await fetch("/api/stripe/checkout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ plan: tier, cycle }),
      });

      if (res.ok) {
        const { url } = await res.json();
        if (url) {
          window.location.href = url;
          return;
        }
      } else if (res.status === 401) {
        // Not signed in → open the auth modal instead of charging.
        window.dispatchEvent(new Event("open-signup"));
        return;
      }
      // 503 (payments not configured) or any other case → demo fallback.
      localStorage.setItem("practiceforge_tier", tier);
      window.location.href = "/practice";
    } catch {
      localStorage.setItem("practiceforge_tier", tier);
      window.location.href = "/practice";
    }
  };

  return (
    <div>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: FAQ.map((item) => ({
              "@type": "Question",
              name: item.q,
              acceptedAnswer: { "@type": "Answer", text: item.a },
            })),
          }),
        }}
      />
      {/* Header */}
      <section className="section" style={{ textAlign: "center", paddingBottom: "4rem" }}>
        <div className="container-sm">
          <div className="badge badge-primary" style={{ marginBottom: "1rem", display: "inline-flex" }}>
             Pricing
          </div>
          <h1 style={{ margin: "0 0 1rem", color: "var(--foreground)" }}>
            Choose your path to mastery
          </h1>
          <p style={{ fontSize: "1.125rem", maxWidth: "550px", margin: "0 auto", color: "var(--foreground-muted)" }}>
            Start for free, or unlock advanced AI examiner features to guarantee your target score.
          </p>
        </div>
      </section>

      {/* Billing cycle toggle */}
      <div style={{ display: "flex", justifyContent: "center", marginBottom: "2.5rem", padding: "0 1.5rem" }}>
        <div role="tablist" aria-label="Billing cycle" style={{ display: "inline-flex", gap: "0.25rem", padding: "0.375rem", background: "var(--surface-2)", border: "1px solid var(--border)", borderRadius: "9999px", flexWrap: "wrap", justifyContent: "center" }}>
          {CYCLES.map((c) => {
            const active = cycle === c.id;
            return (
              <button
                key={c.id}
                role="tab"
                aria-selected={active}
                onClick={() => setCycle(c.id)}
                style={{
                  border: "none", cursor: "pointer", borderRadius: "9999px",
                  padding: "0.5rem 1.25rem", fontSize: "0.875rem", fontWeight: 700,
                  background: active ? "var(--primary)" : "transparent",
                  color: active ? "#fff" : "var(--foreground-muted)",
                  display: "flex", alignItems: "center", gap: "0.5rem", transition: "all 0.15s ease",
                }}
              >
                {c.label}
                {c.badge && (
                  <span style={{ fontSize: "0.6875rem", fontWeight: 800, padding: "0.1rem 0.45rem", borderRadius: "9999px", background: active ? "rgba(255,255,255,0.25)" : "var(--mint)", color: "#fff" }}>
                    {c.badge}
                  </span>
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* 3-TIER PRICING CARDS */}
      <section style={{ padding: "0 1.5rem 6rem" }}>
        <div className="container">
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: "2rem", alignItems: "start" }}>
            
            {/* Starter Plan */}
            <div className="card" style={{ padding: "2.5rem 2rem", display: "flex", flexDirection: "column", height: "100%" }}>
              <h3 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>Starter</h3>
              <p style={{ fontSize: "2.5rem", fontWeight: 800, fontFamily: "var(--font-display)", color: "var(--foreground)", marginBottom: "0.5rem" }}>$0</p>
              <p style={{ fontSize: "0.9375rem", marginBottom: "2rem", color: "var(--foreground-muted)" }}>Immediate value & daily practice for self-studiers.</p>
              
              <ul style={{ listStyle: "none", padding: 0, margin: "0 0 2rem", flex: 1, display: "flex", flexDirection: "column", gap: "1rem" }}>
                {[
                  "1 full practice generation per day",
                  "Includes Mock Tests (up to 15 questions)",
                  "Personal Dictionary (up to 50 words)",
                  "Requires free account signup"
                ].map((feature, i) => (
                  <li key={i} style={{ display: "flex", alignItems: "flex-start", gap: "0.75rem", fontSize: "0.9375rem" }}>
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--mint)" strokeWidth="2" style={{ flexShrink: 0, marginTop: "2px" }}><polyline points="20 6 9 17 4 12"/></svg>
                    <span>{feature}</span>
                  </li>
                ))}
              </ul>
              <button onClick={() => handleUpgrade("free")} className="btn-secondary" style={{ width: "100%", justifyContent: "center", border: "1px solid var(--border)", background: "var(--surface)", color: "var(--foreground)" }}>Create Free Account</button>
            </div>

            {/* Pro Plan */}
            <div className="card" style={{ padding: "2.5rem 2rem", display: "flex", flexDirection: "column", height: "100%", border: "2px solid var(--primary-light)", position: "relative" }}>
              <div style={{ position: "absolute", top: "-14px", left: "50%", transform: "translateX(-50%)", zIndex: 10 }}>
                <span className="badge" style={{ background: "var(--primary)", color: "#fff", padding: "0.375rem 1rem", border: "none", fontWeight: 700, boxShadow: "var(--shadow-sm)" }}>Most Popular</span>
              </div>
              <h3 style={{ fontSize: "1.5rem", marginBottom: "0.5rem", color: "var(--primary)" }}>Pro Study</h3>
              <p style={{ fontSize: "2.5rem", fontWeight: 800, fontFamily: "var(--font-display)", color: "var(--foreground)", marginBottom: "0.25rem" }}>${priceFor("pro", cycle).perMonth}<span style={{ fontSize: "1rem", color: "var(--foreground-muted)", fontWeight: 500 }}>/mo</span></p>
              <p style={{ fontSize: "0.8125rem", marginBottom: "1.25rem", color: "var(--foreground-faint)", minHeight: "1.1rem" }}>{priceFor("pro", cycle).note}</p>
              <p style={{ fontSize: "0.9375rem", marginBottom: "2rem", color: "var(--foreground-muted)" }}>For core students needing comprehensive writing support.</p>
              
              <ul style={{ listStyle: "none", padding: 0, margin: "0 0 2rem", flex: 1, display: "flex", flexDirection: "column", gap: "1rem" }}>
                {[
                  "Unlimited Reading & Writing generation",
                  "Advanced General English Lab",
                  "Line-by-line AI Writing feedback",
                  "Unlimited Personal Dictionary"
                ].map(feature => (
                  <li key={feature} style={{ display: "flex", alignItems: "flex-start", gap: "0.75rem", fontSize: "0.9375rem", fontWeight: 500 }}>
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="2" style={{ flexShrink: 0, marginTop: "2px" }}><polyline points="20 6 9 17 4 12"/></svg>
                    {feature}
                  </li>
                ))}
              </ul>
              <button onClick={() => handleUpgrade("pro")} className="btn-primary" style={{ width: "100%", justifyContent: "center" }}>Upgrade to Pro</button>
            </div>

            {/* Elite Plan */}
            <div className="card-elevated" style={{ padding: "2.5rem 2rem", display: "flex", flexDirection: "column", height: "100%", background: "linear-gradient(135deg, var(--surface) 0%, var(--surface-2) 100%)", borderColor: "var(--gold)", position: "relative" }}>
              <h3 style={{ fontSize: "1.5rem", marginBottom: "0.5rem", color: "var(--gold)" }}>Elite Mastery</h3>
              <p style={{ fontSize: "2.5rem", fontWeight: 800, fontFamily: "var(--font-display)", color: "var(--foreground)", marginBottom: "0.25rem" }}>${priceFor("elite", cycle).perMonth}<span style={{ fontSize: "1rem", color: "var(--foreground-muted)", fontWeight: 500 }}>/mo</span></p>
              <p style={{ fontSize: "0.8125rem", marginBottom: "1.25rem", color: "var(--foreground-faint)", minHeight: "1.1rem" }}>{priceFor("elite", cycle).note}</p>
              <p style={{ fontSize: "0.9375rem", marginBottom: "2rem", color: "var(--foreground-muted)" }}>For students urgently needing Band 7.0+ or 100+.</p>
              
              <ul style={{ listStyle: "none", padding: 0, margin: "0 0 2rem", flex: 1, display: "flex", flexDirection: "column", gap: "1rem" }}>
                {[
                  "Everything in Pro Study",
                  "AI Speaking Evaluations (Daily Token Limit)",
                  "Unlimited Mock Tests",
                  "Guaranteed Score Acceleration Path"
                ].map(feature => (
                  <li key={feature} style={{ display: "flex", alignItems: "flex-start", gap: "0.75rem", fontSize: "0.9375rem", fontWeight: 600 }}>
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--gold)" strokeWidth="2" style={{ flexShrink: 0, marginTop: "2px" }}><polyline points="20 6 9 17 4 12"/></svg>
                    {feature}
                  </li>
                ))}
              </ul>
              <button onClick={() => handleUpgrade("elite")} className="btn-primary" style={{ width: "100%", justifyContent: "center", background: "linear-gradient(135deg, #F59E0B, #D97706)", boxShadow: "0 4px 14px 0 rgba(245, 158, 11, 0.39)" }}>Get Elite Mastery</button>
            </div>

          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="section" style={{ paddingTop: "2rem", background: "var(--surface-2)" }}>
        <div className="container-sm">
          <h2 style={{ color: "var(--foreground)", marginBottom: "3rem", textAlign: "center" }}>
            Frequently asked questions
          </h2>
          <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
            {FAQ.map((item) => (
              <div key={item.q} className="card" style={{ padding: "1.5rem" }}>
                <h3 style={{ margin: "0 0 0.75rem", fontSize: "1.125rem", color: "var(--foreground)" }}>
                  {item.q}
                </h3>
                <p style={{ margin: 0, fontSize: "1rem", lineHeight: 1.6, color: "var(--foreground-muted)" }}>{item.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
